apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: jenkins-build-node-affinity
spec:
  applyTo:
    - groups: [""]
      kinds: [Pod]
      versions: [v1]
  match:
    scope: Namespaced
    kinds:
      - apiGroups: [v1]
        kinds: [Pod]
    labelSelector:
      matchLabels:
        cloudogu.com/pod-kind: jenkins-build
  location: "spec.affinity"
  parameters:
    assign:
      value:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: reserved-node
                    operator: In
                    values:
                      - jenkins-build
---
apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: jenkins-build-node-tolerations
spec:
  applyTo:
    - groups: [""]
      kinds: [Pod]
      versions: [v1]
  match:
    scope: Namespaced
    kinds:
      - apiGroups: [v1]
        kinds: [Pod]
    labelSelector:
      matchLabels:
        cloudogu.com/pod-kind: jenkins-build
  location: "spec.tolerations"
  parameters:
    assign:
      value:
        - key: reserved-node
          operator: Equal
          value: jenkins-build
          effect: NoSchedule