apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: jenkins-build-node-tolerations
spec:
  applyTo:
    - groups: [""]
      kinds: [Pod]
      versions: [v1]
  match:
    scope: Namespaced
    namespaces: [jenkins-build]
    kinds:
      - apiGroups: [v1]
        kinds: [Pod]
  location: "spec.tolerations"
  parameters:
    assign:
      value:
        - key: reserved-node
          operator: Equal
          value: jenkins-build
          effect: NoSchedule