apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: jenkins-build-node-affinity
spec:
  applyTo:
    - groups: [""]
      kinds: [Pod]
      versions: [v1]
  match:
    scope: Namespaced
    namespaces: [jenkins-build]
    kinds:
      - apiGroups: [v1]
        kinds: [Pod]
  location: "spec.affinity"
  parameters:
    assign:
      value:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: reserved-node
                    operator: In
                    values:
                      - jenkins-build